"""Audit conformance — runs `scitex-dev ecosystem audit-all`
on this package as a normal pytest test. Generated by
`scitex-dev ecosystem write-audit-test`. Re-run that command
after upgrading scitex-dev to refresh any pin in [dev].
"""

import shutil

import pytest

pytestmark = pytest.mark.skipif(
    shutil.which("scitex-dev") is None,
    reason=(
        "scitex-dev not installed — add `scitex-dev[cli-audit]` "
        "to [project.optional-dependencies.dev]"
    ),
)


def test_audit_all_for_package_returns_clean():
    # Arrange
    from scitex_dev.testing import audit_all_for_package

    # Act — raises on any audit failure; absence of exception == success
    audit_all_for_package("scitex-compat")
    audit_succeeded = True

    # Assert
    assert audit_succeeded is True
